### PR TITLE
Group scripts and added the README to database directory

### LINKED ISSUE #97: Create a script for handling NSI geojson to NSI building inventory geopackage file
Create a script to convert geojson file to NSI based IN-CORE building inventory geopackage file. This should include
1. need to handle the state based geojson data
2. need to automatically figure out the location of the geojson for the NSI building inventory conversion, such as 'westcoast', 'midwest', and eastcoast'
3. need to handle zip file. The state geojsons are in zip format. The script should unzip, process it, then removed unzipped file
4. need to handle the directory base. Instead of providing one file by one, capture every zip file in the directory, then process every zip file.
5. need to zip prcessed gpkg file.

### LINKED ISSUE #98: Create a documentation of the README file for the NSI related scripts
Currently, there are many scripts related to NSI data and handling. It needs to have a README file that explains the purpose and usage of the scripts. Created one so the users can understand about the scripts related to NSI data handling.

### LINKED ISSUE #99: Find a method or ingesting the NSI building inventory data to PostGIS database in kubernetes without disconnection error
When using the kubernetes port-forward option, ingestion of the postgis data can be very painful due to the port-forward disconnection error. This happens very often so I have tried to resolver this issue by doing
1: converted geojson to sql command that speepds up the process
2: subdivided geojson / sql to the smaller chunks so it can finish quickly
3: created the resources of the postgres pod in kube clusters

However, the efforts avoid made the process way more stable, but never resolved the issue completely. Therefore, I need to figure out new way of the ingestion that doesn't use the port-forward at all. This could be done by doing 
1: convert geojson to sql in local
2: move sql to the postgres pod (into the mounted directory_
3: run insertion using the sql in the actual pod
4: clean up

This probably will resolve the port-forward issue. I need to figure out if this process is feasible in real situation.

### LINKED ISSUE #102: Record the postgres view file that used for the NSI building inventory query
We need to create a database view to standardize and simplify the export of building inventory shapefiles. This view should handle:

It will benefit:
- Reduces logic and mapping in Java code
- Prevents mismatches and missing values in exported shapefiles
- Simplifies feature writing logic in Java code

Example usage:
The Java backend now queries this view directly when exporting shapefiles, relying on the view to present properly formatted columns.

### LINKED ISSUE #103: kubectl cp fails when copying large SQL file (~1GB+): unexpected EOF
When attempting to ingest large NSI datasets via `ingest_zipped_gpkg.sh`, the `kubectl cp` command fails with the following error:

```
Unhandled Error" err="next reader: websocket: close 1006 (abnormal closure): unexpected EOF
```

This happens even after compressing the file into `.tar.gz`, and seems to be caused by the file size (approx. 1 GB). As a result, the ingestion fails. This needs to be fixed to keep going, and breaking the SQL file into smaller chunks and executing them one by one.

### LINKED ISSUE #104: Update NSI view to handle the newly updated fields in the NSI building inventory data
There are four new fields updated in NSI building inventory data. These should be added to the NSI query view in the postgres database. Update the view sql and deploy it to both prod and dev database.

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

File: NSI/database/ingest_geojson_to_postgis.sh [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+if [ -z "$1" ]; then
+  echo "Usage: $0 <geojson-file> [overwrite|append]"
+  exit 1
+fi
+
+GEOJSON_FILE="$1"
+IMPORT_MODE=${2:-append}  # Default to "append" if not specified
+
+# === CONFIGURATION ===
+NAMESPACE="incore"
```
Comment (navarroc) [inline NSI/database/ingest_geojson_to_postgis.sh:46]: This would be more flexible if we allowed the configuration to be set from the environment. With bash, we could do something like this:

```
NAMESPACE=${NAMESPACE:="incore"}
```

This will accomplish what you want if nothing is set by the user and still allow a user to optionally override values that could change.

**Comment by navarroc** [comment]
It's minor, but can you set the executable flag on the shell scripts? Looks like none of them are set to executable from what I can see. I think you can do this like this on windows:

```
git add --chmod=+x geojson_to_sql_append.sh
```

File: NSI/database/ingest_geojson_to_postgis.sh (hunk 1 above)
Comment (ywkim312) [reply NSI/database/ingest_geojson_to_postgis.sh:46]: no one else will use it

**Review by navarroc — APPROVED** [review]
